const UPDATE_CONTACT_LIST = "UPDATE_CONTACT_LIST";
const HANDLE_MODAL_DISPLAY = "HANDLE_MODAL_DISPLAY";
// const DELETE_CONTACT = "HANDLE_DELETE_CONTACT";
// const UPDATE_STARRED_CONTACT = "HANDLE_STARRED_CONTACT";

export { UPDATE_CONTACT_LIST, HANDLE_MODAL_DISPLAY};